"use client";

import { useEffect, useState } from "react";
import { ChefHat, Clock3, Printer, RefreshCw, CheckCircle2, PlayCircle, XCircle, QrCode, Beaker } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import Sidebar from "../components/Sidebar";
import "./wise-kitchen.css";

type Ingredient={name:string;quantity:number;unit:string};
type Item={product_name:string;quantity:number;unit_price:number;line_total:number;options?:Record<string,unknown>;ingredients?:Ingredient[]};
type Order={id:string;order_no:string;customer_name:string;notes:string|null;status:string;total:number;created_at:string;items:Item[]};
const esc=(v:unknown)=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]!));

export default function WiseKitchen(){
 const [orders,setOrders]=useState<Order[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/wise-kitchen/orders",{cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to load kitchen orders");setOrders(x.orders||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);
 const process=async(id:string,status:string)=>{setBusy(`${id}:${status}`);try{const r=await fetch("/api/wise-kitchen/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({order_id:id,status})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to update order");await load()}catch(e:any){alert(e.message)}finally{setBusy("")}};
 const statusUrl=(o:Order)=>`${window.location.origin}/menu/status?order=${encodeURIComponent(o.order_no)}`;
 const printSticker=(o:Order)=>{const el=document.getElementById(`sticker-${o.id}`);const svg=el?.querySelector("svg")?.outerHTML;if(!svg)return;const w=window.open("","_blank","width=420,height=500");if(!w)return;w.document.write(`<html><head><title>${esc(o.order_no)} Cup Sticker</title><style>@page{size:58mm 58mm;margin:0}*{box-sizing:border-box}body{margin:0;width:58mm;min-height:58mm;font-family:Arial,sans-serif;color:#111;display:flex;align-items:center;justify-content:center}.sticker{width:52mm;min-height:52mm;border:1px solid #111;padding:4mm;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2.5mm}.sticker svg{width:30mm;height:30mm}.customer{font-size:13px;font-weight:800}.order{font-size:11px;font-weight:700}.hint{font-size:8px;color:#555}</style></head><body><div class="sticker">${svg}<div class="customer">${esc(o.customer_name)}</div><div class="order">${esc(o.order_no)}</div><div class="hint">Scan for order status</div></div></body></html>`);w.document.close();setTimeout(()=>w.print(),250)};
 const printKot=(o:Order)=>{const w=window.open("","_blank","width=420,height=700");if(!w)return;const items=o.items.map(i=>`<div class="item"><span class="qty">${esc(i.quantity)} × ${esc(i.product_name)}</span>${(i.ingredients||[]).map(g=>`<div class="ing">• ${esc(g.quantity)} ${esc(g.unit)} ${esc(g.name)}</div>`).join("")}</div>`).join("");w.document.write(`<html><head><title>${esc(o.order_no)} KOT</title><style>body{font-family:Arial,sans-serif;width:360px;margin:20px;color:#111}.center{text-align:center}.line{border-top:1px dashed #777;margin:12px 0}.item{margin:12px 0}.qty{font-size:20px;font-weight:800}.ing{margin:4px 0 0 22px;font-size:13px}small{color:#555}</style></head><body><div class="center"><h2>WISE KITCHEN</h2><b>KITCHEN ORDER TICKET</b></div><div class="line"></div><b>${esc(o.order_no)}</b><br>Customer: ${esc(o.customer_name)}<br>${esc(new Date(o.created_at).toLocaleString())}<div class="line"></div>${items}${o.notes?`<div class="line"><b>NOTES</b><br>${esc(o.notes)}</div>`:""}<div class="line"></div><div class="center">KOT • ${esc(o.order_no)}</div></body></html>`);w.document.close();setTimeout(()=>w.print(),150)};
 return <div className="wk-shell"><Sidebar/><main className="wk-main"><header className="wk-header"><div><div className="wk-kicker"><ChefHat size={16}/> WISE KITCHEN</div><h1>Kitchen Receiving</h1><p>Live customer orders from WISE MENU.</p></div><div className="wk-header-actions"><a href="/wise-kitchen/recipes"><Beaker size={16}/> Recipes</a><button onClick={load}><RefreshCw size={16}/> Refresh</button></div></header>{error&&<div className="wk-error">{error}</div>}<div className="wk-status"><span><i/> New {orders.filter(o=>o.status==="new").length}</span><span><i/> Preparing {orders.filter(o=>o.status==="preparing").length}</span><span><i/> Ready {orders.filter(o=>o.status==="ready").length}</span></div>{loading&&!orders.length?<div className="wk-empty">Loading kitchen orders…</div>:!orders.length?<div className="wk-empty"><ChefHat size={30}/><b>No kitchen orders</b><span>New WISE MENU orders will appear here automatically.</span></div>:<section className="wk-grid">{orders.map(o=><article className={`wk-card status-${o.status}`} key={o.id}><header><div><b>{o.order_no}</b><small><Clock3 size={12}/> {new Date(o.created_at).toLocaleString()}</small></div><strong>{o.status.toUpperCase()}</strong></header><div className="wk-customer"><span>Customer</span><b>{o.customer_name}</b></div><div className="wk-items">{o.items.map((i,n)=><div className="wk-item" key={`${o.id}-${n}`}><div><b><em>{i.quantity}×</em> {i.product_name}</b>{i.ingredients?.length?<div className="wk-ingredients">{i.ingredients.map((g,j)=><span key={j}>{g.quantity} {g.unit} {g.name}</span>)}</div>:<small>Recipe not configured</small>}</div></div>)}</div>{o.notes&&<div className="wk-notes"><b>NOTE</b>{o.notes}</div>}<footer><button onClick={()=>printKot(o)}><Printer size={15}/> KOT</button><button onClick={()=>printSticker(o)}><QrCode size={15}/> Cup Sticker</button><button onClick={()=>process(o.id,"cancelled")} disabled={!!busy}><XCircle size={15}/> Cancel</button>{o.status==="new"&&<button className="primary" onClick={()=>process(o.id,"preparing")} disabled={!!busy}><PlayCircle size={15}/> Start Preparing</button>}{o.status==="preparing"&&<button className="primary" onClick={()=>process(o.id,"ready")} disabled={!!busy}><CheckCircle2 size={15}/> Mark Ready</button>}{o.status==="ready"&&<button className="primary" onClick={()=>process(o.id,"served")} disabled={!!busy}><CheckCircle2 size={15}/> Served</button>}</footer><div id={`sticker-${o.id}`} className="wk-sticker"><QRCodeSVG value={statusUrl(o)} size={92} level="M"/><b>{o.customer_name}</b><strong>{o.order_no}</strong><small>Customer/order identification only</small><span>Place sticker beside cup lid/cap</span></div></article>)}</section>}</main></div>;
}
