"use client";

import { useEffect, useMemo, useState } from "react";
import { Calculator, Check, Loader2, Percent, RotateCcw, Save, Settings2, WalletCards } from "lucide-react";
import Sidebar from "../components/Sidebar";
import { supabase } from "../../lib/supabase";
import "../pos/pos.css";

type Pricing = { id?: string; business_id: string; currency: string; paper_a4_cost:number; paper_legal_cost:number; paper_letter_cost:number; paper_photo_cost:number; paper_sticker_cost:number; bw_light_rate:number; bw_medium_rate:number; bw_heavy_rate:number; color_light_rate:number; color_medium_rate:number; color_heavy_rate:number; machine_cost_per_page:number; labor_cost_per_job:number; waste_allowance_percent:number; markup_percent:number; minimum_job_price:number; round_to:number; minimum_bw_page_price:number; minimum_color_light_page_price:number; minimum_color_medium_page_price:number; minimum_color_heavy_page_price:number; };
const defaults: Pricing = { business_id:"default",currency:"PHP",paper_a4_cost:0,paper_legal_cost:0,paper_letter_cost:0,paper_photo_cost:0,paper_sticker_cost:0,bw_light_rate:0,bw_medium_rate:0,bw_heavy_rate:0,color_light_rate:0,color_medium_rate:0,color_heavy_rate:0,machine_cost_per_page:0,labor_cost_per_job:0,waste_allowance_percent:0,markup_percent:0,minimum_job_price:0,round_to:0,minimum_bw_page_price:2,minimum_color_light_page_price:3,minimum_color_medium_page_price:5,minimum_color_heavy_page_price:8 };
const money = (n:number) => `₱${Number(n||0).toFixed(2)}`;

export default function SmartPricingPage(){
 const [p,setP]=useState<Pricing>(defaults); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [warning,setWarning]=useState("");
 const set=(k:keyof Pricing,v:any)=>{setP(x=>({...x,[k]:v}));setMessage("")};
 useEffect(()=>{(async()=>{try{const {data,error}=await supabase.from("smart_pricing_settings").select("*").eq("business_id","default").maybeSingle(); if(error) throw error; if(data)setP({...defaults,...data});}catch{setWarning("Smart Pricing database is not active yet. Run the updated supabase_smart_pricing_settings.sql in Supabase to sync these settings.");}finally{setLoading(false)}})()},[]);
 const save=async()=>{setSaving(true);setMessage("");try{const {error}=await supabase.from("smart_pricing_settings").upsert({...p,business_id:"default"},{onConflict:"business_id"});if(error)throw error;setMessage("Smart Pricing Settings saved successfully.");}catch{setWarning("Unable to save to Supabase. Please run the updated supabase_smart_pricing_settings.sql first.");}finally{setSaving(false)}};
 const sample=useMemo(()=>{const pages=10;const material=pages*p.paper_a4_cost;const ink=6*p.bw_light_rate+3*p.bw_medium_rate+p.bw_heavy_rate;const machine=pages*p.machine_cost_per_page;const labor=p.labor_cost_per_job;const base=material+ink+machine+labor;const waste=base*p.waste_allowance_percent/100;const cost=base+waste;const costPrice=cost*(1+p.markup_percent/100);const pageFloor=10*p.minimum_bw_page_price;const suggested=Math.max(p.minimum_job_price,costPrice,pageFloor);const rounded=p.round_to>0?Math.ceil(suggested/p.round_to)*p.round_to:suggested;return{material,ink,machine,labor,waste,cost,pageFloor,price:rounded}},[p]);
 if(loading)return <main className="app-shell"><Sidebar/><section className="workspace"><div style={{padding:40,display:"flex",gap:10,alignItems:"center"}}><Loader2 className="spin"/>Loading Smart Pricing Settings...</div></section></main>;
 const Field=({label,k,step=0.01}:{label:string;k:keyof Pricing;step?:number})=><label className="sp-field"><span>{label}</span><input type="number" min="0" step={step} value={Number(p[k])||0} onChange={e=>set(k,Number(e.target.value)||0)}/></label>;
 return <main className="app-shell"><Sidebar/><section className="workspace" style={{padding:"28px 32px",maxWidth:1600}}>
 <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"center",marginBottom:20}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:".12em",color:"#b21f1f",display:"flex",gap:7,alignItems:"center"}}><Settings2 size={16}/> SMART PRICING ENGINE</div><h1 style={{margin:"7px 0 5px"}}>Smart Pricing Settings</h1><p style={{margin:0,color:"#6b7280"}}>Set your real printing costs and minimum customer selling prices. Smart Computation will never go below your price floors.</p></div><div style={{display:"flex",gap:10}}><button className="sp-btn secondary" onClick={()=>setP(defaults)}><RotateCcw size={17}/>Reset</button><button className="sp-btn primary" onClick={save} disabled={saving}>{saving?<Loader2 className="spin" size={17}/>:<Save size={17}/>} {saving?"SAVING...":"SAVE SETTINGS"}</button></div></header>
 {message&&<div className="sp-alert ok"><Check size={17}/>{message}</div>}{warning&&<div className="sp-alert warn">{warning}</div>}
 <div className="sp-grid">
 <section className="sp-card"><h2>📄 Paper & Material Cost</h2><p>Enter your actual cost per sheet.</p><div className="sp-fields"><Field label="A4 Bond Paper (₱/sheet)" k="paper_a4_cost"/><Field label="Legal Bond Paper (₱/sheet)" k="paper_legal_cost"/><Field label="Letter Paper (₱/sheet)" k="paper_letter_cost"/><Field label="Photo Paper (₱/sheet)" k="paper_photo_cost"/><Field label="Sticker Paper (₱/sheet)" k="paper_sticker_cost"/></div></section>
 <section className="sp-card"><h2>⚫ Black & White Ink Rates</h2><p>Estimated ink cost per analyzed page.</p><div className="sp-fields"><Field label="Light Coverage (₱/page)" k="bw_light_rate"/><Field label="Medium Coverage (₱/page)" k="bw_medium_rate"/><Field label="Heavy Coverage (₱/page)" k="bw_heavy_rate"/></div></section>
 <section className="sp-card"><h2>🌈 Color Ink Rates</h2><p>Use separate rates because color printing consumes different materials.</p><div className="sp-fields"><Field label="Light Coverage (₱/page)" k="color_light_rate"/><Field label="Medium Coverage (₱/page)" k="color_medium_rate"/><Field label="Heavy Coverage (₱/page)" k="color_heavy_rate"/></div></section>
 <section className="sp-card"><h2>🛡️ Customer Price Floors</h2><p>Minimum selling price per page. The Smart Price will use the higher amount between actual cost calculation and these floors.</p><div className="sp-fields"><Field label="B&W Minimum (₱/page)" k="minimum_bw_page_price"/><Field label="Color Light Minimum (₱/page)" k="minimum_color_light_page_price"/><Field label="Color Medium Minimum (₱/page)" k="minimum_color_medium_page_price"/><Field label="Color Heavy / Images Minimum (₱/page)" k="minimum_color_heavy_page_price"/></div></section>
 <section className="sp-card"><h2>⚙️ Production & Profit Rules</h2><p>Additional costs and the final business pricing rules.</p><div className="sp-fields"><Field label="Machine Cost (₱/page)" k="machine_cost_per_page"/><Field label="Labor Cost (₱/job)" k="labor_cost_per_job"/><Field label="Waste Allowance (%)" k="waste_allowance_percent"/><Field label="Markup / Profit (%)" k="markup_percent"/><Field label="Minimum Job Price (₱)" k="minimum_job_price"/><Field label="Round Final Price To (₱)" k="round_to" step={1}/></div></section>
 <aside className="sp-card sp-preview"><div className="sp-preview-icon"><Calculator size={24}/></div><span>LIVE SAMPLE</span><h2>10-page A4 document</h2><p>6 B&W Light · 3 B&W Medium · 1 B&W Heavy</p><div className="sp-row"><span>Material</span><b>{money(sample.material)}</b></div><div className="sp-row"><span>Estimated Ink</span><b>{money(sample.ink)}</b></div><div className="sp-row"><span>Machine</span><b>{money(sample.machine)}</b></div><div className="sp-row"><span>Labor</span><b>{money(sample.labor)}</b></div><div className="sp-row"><span>Waste Allowance</span><b>{money(sample.waste)}</b></div><div className="sp-row total"><span>Production Cost</span><b>{money(sample.cost)}</b></div><div className="sp-row"><span>B&W Page Price Floor</span><b>{money(sample.pageFloor)}</b></div><div className="sp-price">SUGGESTED PRICE<strong>{money(sample.price)}</strong></div><small><Percent size={14}/> Uses actual cost, markup, job minimum, page price floors and rounding rules.</small></aside>
 </div>
 <style jsx global>{`.sp-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr)) 340px;gap:18px}.sp-card{background:#fff;border:1px solid #e3e7eb;border-radius:18px;padding:22px;box-shadow:0 8px 25px rgba(20,30,40,.04)}.sp-card h2{margin:0 0 5px;font-size:19px;color:#262a2f}.sp-card>p{margin:0 0 18px;color:#737a81;font-size:13px}.sp-fields{display:grid;grid-template-columns:1fr 1fr;gap:13px}.sp-field{display:flex;flex-direction:column;gap:7px}.sp-field span{font-size:12px;font-weight:750;color:#59616a}.sp-field input{border:1px solid #dfe4e8;border-radius:10px;padding:11px 12px;font-size:15px;outline:none}.sp-field input:focus{border-color:#c72a2a;box-shadow:0 0 0 3px rgba(199,42,42,.08)}.sp-btn{display:inline-flex;align-items:center;gap:8px;border-radius:10px;padding:11px 16px;font-weight:800;cursor:pointer}.sp-btn.primary{background:#bf1d1d;color:#fff;border:1px solid #bf1d1d}.sp-btn.secondary{background:#fff;border:1px solid #dfe4e8}.sp-alert{padding:12px 14px;border-radius:10px;margin-bottom:14px;display:flex;gap:8px;align-items:center}.sp-alert.ok{background:#edf9f1;color:#257142}.sp-alert.warn{background:#fff7e8;color:#9a650b}.sp-preview{grid-column:3;grid-row:1 / span 3;background:linear-gradient(160deg,#fff,#fff8f8)}.sp-preview-icon{width:48px;height:48px;border-radius:14px;display:grid;place-items:center;background:#ffe9e9;color:#b92020;margin-bottom:15px}.sp-preview>span{font-size:10px;letter-spacing:.14em;font-weight:850;color:#b92020}.sp-preview h2{margin-top:8px}.sp-row{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #eceff1;color:#616970}.sp-row.total{color:#262b30;font-weight:800}.sp-price{margin-top:18px;padding:16px;border-radius:14px;background:#c51e1e;color:#fff;font-size:11px;font-weight:850;letter-spacing:.1em}.sp-price strong{display:block;font-size:31px;letter-spacing:0;margin-top:5px}.sp-preview small{margin-top:14px;display:flex;gap:6px;align-items:center;color:#6d747b}@media(max-width:1250px){.sp-grid{grid-template-columns:1fr 1fr}.sp-preview{grid-column:1/-1;grid-row:auto}}@media(max-width:760px){.sp-grid{grid-template-columns:1fr}.sp-fields{grid-template-columns:1fr}.sp-preview{grid-column:auto} .workspace{padding:20px!important}}`}</style>
 </section></main>;
}
