"use client";
import { useCallback, useEffect, useState } from "react";
import { Check, ChevronRight, Copy, ExternalLink, Mail, Printer, QrCode, RefreshCw, ScanLine, Send, Smartphone, UserRound, Utensils, X } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { supabase } from "../../lib/supabase";
import Sidebar from "../components/Sidebar";
import "./wise-menu.css";

type Item={product_id:string;product_name:string;quantity:number;unit_price:number;line_total:number;options?:any};
type Order={id:string;order_no:string;customer_name:string;customer_email?:string|null;notes?:string|null;status:string;order_type?:"dine_in"|"take_out"|null;subtotal:number;total:number;created_at:string;wise_menu_order_items:Item[]};
const wait=(ms:number)=>new Promise(resolve=>window.setTimeout(resolve,ms));
const displayStatus=(status:string)=>status==="accepted"?"pending":status;
const displayType=(type?:string|null)=>type==="dine_in"?"Dine In":"Take Out";

export default function WiseMenuPage(){
 const [origin,setOrigin]=useState("");const [copied,setCopied]=useState(false);const [orders,setOrders]=useState<Order[]>([]);const [loading,setLoading]=useState(false);const [selected,setSelected]=useState<Order|null>(null);const [sending,setSending]=useState(false);const [message,setMessage]=useState("");const [tab,setTab]=useState<"new"|"pending">("new");
 useEffect(()=>setOrigin(window.location.origin),[]);
 const base=origin||"https://print-wise-pos.vercel.app",menuUrl=`${base}/menu/order`;
 const getToken=async()=>{for(let attempt=0;attempt<4;attempt++){const {data}=await supabase.auth.getSession();if(data.session?.access_token)return data.session.access_token;if(attempt<3)await wait(250)}return ""};
 const loadOrders=useCallback(async()=>{setLoading(true);try{const token=await getToken();if(!token){setMessage("Please sign in to the cashier account to receive WISE MENU orders.");return}const r=await fetch("/api/wise-menu/receiving",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to load orders");const incoming=(x.orders||[]).slice().sort((a:Order,b:Order)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime());setOrders(incoming);setMessage("");}catch(e:any){setMessage(e.message||"Unable to load orders")}finally{setLoading(false)}},[]);
 useEffect(()=>{let active=true;const boot=async()=>{const token=await getToken();if(active&&token)loadOrders()};boot();const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{if(session?.access_token)window.setTimeout(()=>{if(active)loadOrders()},0)});const t=window.setInterval(()=>{if(active&&document.visibilityState==="visible")loadOrders()},10000);return()=>{active=false;subscription.unsubscribe();window.clearInterval(t)}},[loadOrders]);
 const copyLink=async()=>{try{await navigator.clipboard.writeText(menuUrl);setCopied(true);window.setTimeout(()=>setCopied(false),1600)}catch{}};
 const sendToPos=async()=>{if(!selected||sending)return;setSending(true);try{const token=await getToken();if(!token)throw new Error("Please sign in to the cashier account.");const r=await fetch("/api/wise-menu/receiving",{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({order_id:selected.id})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to confirm order");if(!x?.ok)throw new Error("WISE MENU order was not accepted.");setSelected(null);setTab("pending");await loadOrders();window.location.assign(`/pos?wiseMenuOrder=${encodeURIComponent(selected.id)}`);}catch(e:any){setMessage(e.message||"Unable to confirm order");setSending(false)}};
 const visibleOrders=orders.filter(o=>tab==="new"?o.status==="new":o.status==="accepted");
 const newCount=orders.filter(o=>o.status==="new").length,pendingCount=orders.filter(o=>o.status==="accepted").length;
 return <div className="wise-menu-shell"><Sidebar/><main className="wise-menu-main">
 <header className="wise-receiving-header"><div><div className="wise-menu-kicker"><QrCode size={15}/> WISE MENU RECEIVING PORTAL</div><h1>WISE MENU</h1><p>Cashier receiving portal — review customer order files before sending them to POS.</p></div><div className="wise-receiving-actions"><button onClick={loadOrders}><RefreshCw size={16}/> Refresh</button><button onClick={()=>window.print()}><Printer size={16}/> Print QR</button></div></header>
 <section className="receiving-hero"><div className="receiving-hero-icon"><ScanLine size={28}/></div><div className="receiving-hero-copy"><span>UNIVERSAL CUSTOMER QR</span><h2>One QR Code. One WISE MENU.</h2><p>One QR for all customers. Orders first arrive here for cashier verification.</p></div><div className="receiving-flow"><div><QrCode size={18}/><b>SCAN</b><small>Universal QR</small></div><Send size={16}/><div><Smartphone size={18}/><b>ORDER</b><small>Customer phone</small></div><Send size={16}/><div><UserRound size={18}/><b>CONFIRM</b><small>Cashier review</small></div></div></section>
 <section className="wise-universal-qr-wrap"><article className="wise-universal-qr-card"><div className="universal-label">WISE MENU</div><h2>SCAN TO ORDER</h2><p className="universal-subtitle">Use your phone camera to open the customer menu</p><div className="universal-qr-box"><QRCodeSVG value={menuUrl} size={300} level="M" includeMargin/></div><div className="universal-qr-badge"><QrCode size={14}/> UNIVERSAL QR CODE</div><div className="universal-actions"><a href={menuUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Open Menu</a><button onClick={copyLink}><Copy size={15}/> {copied?"Copied":"Copy Link"}</button><button onClick={()=>window.print()}><Printer size={15}/> Print QR</button></div><div className="universal-url">{menuUrl}</div></article><aside className="wise-universal-info"><div className="info-kicker">WORKFLOW</div><h3>Customer → Cashier → POS → Payment</h3><div className="info-step"><span>01</span><div><b>SCAN & ORDER</b><small>Customer uses the one universal QR.</small></div></div><div className="info-step"><span>02</span><div><b>RECEIVE</b><small>New order appears as Pending Review.</small></div></div><div className="info-step"><span>03</span><div><b>VIEW</b><small>Cashier checks customer, items, quantity, notes and total.</small></div></div><div className="info-step"><span>04</span><div><b>CONFIRM</b><small>Confirmed order remains visible under Pending.</small></div></div><div className="info-step"><span>05</span><div><b>CURRENT SALE</b><small>Cashier opens the confirmed order in POS Current Sale.</small></div></div><div className="info-step"><span>06</span><div><b>PAYMENT</b><small>Cashier completes payment in POS.</small></div></div></aside></section>
 <section className="wise-orders-panel"><div className="wise-orders-head"><div><span className="wise-menu-kicker">CUSTOMER ORDERS</span><h2>Incoming Orders</h2><p>New orders need review. Confirmed unpaid orders stay visible as <b>Pending</b>.</p></div><div className="wise-live"><i/> LIVE · {newCount+pendingCount} orders</div></div>
 <div className="wise-order-tabs"><button className={tab==="new"?"active":""} onClick={()=>setTab("new")}>New Orders <b>{newCount}</b></button><button className={tab==="pending"?"active":""} onClick={()=>setTab("pending")}>Pending Orders <b>{pendingCount}</b></button></div>
 {message&&<div className="wise-order-message">{message}<button onClick={()=>setMessage("")}><X size={15}/></button></div>}
 {loading&&visibleOrders.length===0?<div className="wise-orders-empty">Loading customer orders…</div>:visibleOrders.length===0?<div className="wise-orders-empty"><Smartphone size={30}/><b>{tab==="new"?"No new customer orders":"No pending customer orders"}</b><span>{tab==="new"?"New WISE MENU orders will appear here automatically.":"Confirmed unpaid orders will remain here until payment is completed."}</span></div>:<div className="wise-orders-table-wrap"><table className="wise-orders-table"><thead><tr><th>Order</th><th>Customer</th><th>Type</th><th>Date / Time</th><th>Items</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{visibleOrders.map(o=><tr key={o.id}><td><b>{o.order_no}</b></td><td><div className="wise-customer-cell"><UserRound size={15}/><div><b>{o.customer_name}</b><small>{o.customer_email||"No email"}</small></div></div></td><td>{displayType(o.order_type)}</td><td>{new Date(o.created_at).toLocaleString()}</td><td>{o.wise_menu_order_items.reduce((n,i)=>n+i.quantity,0)}</td><td><b>₱{Number(o.total).toFixed(2)}</b></td><td><span className={`wise-status ${o.status}`}>{displayStatus(o.status)}</span></td><td><button className="wise-view-btn" onClick={()=>setSelected(o)}>View <ChevronRight size={15}/></button></td></tr>)}</tbody></table></div>}
 </section>
 {selected&&<div className="wise-order-overlay" onClick={()=>setSelected(null)}><section className="wise-order-modal" onClick={e=>e.stopPropagation()}><header><div><span>WISE MENU ORDER FILE</span><h2>{selected.order_no}</h2></div><button onClick={()=>setSelected(null)}><X/></button></header><div className="wise-order-customer"><div><UserRound size={17}/><div><small>Customer</small><b>{selected.customer_name}</b></div></div><div><Mail size={17}/><div><small>Email</small><b>{selected.customer_email||"—"}</b></div></div><div><Utensils size={17}/><div><small>Receive</small><b>{displayType(selected.order_type)}</b></div></div><span className={`wise-status ${selected.status}`}>{displayStatus(selected.status)}</span></div><div className="wise-order-items"><h3>Customer Order</h3>{selected.wise_menu_order_items.map((i,n)=><div className="wise-order-item" key={`${i.product_id}-${n}`}><div><b>{i.product_name}</b><small>{i.quantity} × ₱{Number(i.unit_price).toFixed(2)}</small></div><strong>₱{Number(i.line_total).toFixed(2)}</strong></div>)}</div>{selected.notes&&<div className="wise-order-notes"><b>Special Instructions</b><p>{selected.notes}</p></div>}<div className="wise-order-total"><span>Total</span><b>₱{Number(selected.total).toFixed(2)}</b></div><footer><button className="wise-cancel-btn" onClick={()=>setSelected(null)}>Close</button>{selected.status==="new"?<button className="wise-confirm-btn" onClick={sendToPos} disabled={sending}>{sending?<><RefreshCw className="spin" size={17}/> Opening Current Sale…</>:<><Check size={17}/> Confirm & Open Current Sale</>}</button>:<button className="wise-confirm-btn" onClick={()=>window.location.assign(`/pos?wiseMenuOrder=${encodeURIComponent(selected.id)}`)}><ChevronRight size={17}/> Open in Current Sale</button>}</footer></section></div>}
 </main></div>;
}
