"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, Minus, Plus, ShoppingBag, X } from "lucide-react";
import "./menu.css";

type Product = { id:string; name:string; category:string|null; description:string|null; price:number; unit:string|null; image_url:string|null; video_url:string|null };
type CartItem = { product:Product; quantity:number };

export default function WiseMenuOrder() {
  const [products,setProducts]=useState<Product[]>([]); const [cart,setCart]=useState<CartItem[]>([]); const [category,setCategory]=useState("All"); const [search,setSearch]=useState(""); const [name,setName]=useState(""); const [notes,setNotes]=useState(""); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [success,setSuccess]=useState<any>(null); const [cartOpen,setCartOpen]=useState(false);
  useEffect(()=>{ fetch("/api/menu/products").then(r=>r.json()).then(x=>setProducts(x.products||[])).catch(()=>setProducts([])).finally(()=>setLoading(false)); },[]);
  const categories=useMemo(()=>["All",...Array.from(new Set(products.map(p=>p.category).filter(Boolean) as string[]))],[products]);
  const filtered=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&`${p.name} ${p.description||""}`.toLowerCase().includes(search.toLowerCase())),[products,category,search]);
  const total=cart.reduce((s,x)=>s+x.product.price*x.quantity,0); const count=cart.reduce((s,x)=>s+x.quantity,0);
  const add=(p:Product)=>setCart(c=>{const x=c.find(i=>i.product.id===p.id); return x?c.map(i=>i.product.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{product:p,quantity:1}]});
  const change=(id:string,d:number)=>setCart(c=>c.map(i=>i.product.id===id?{...i,quantity:i.quantity+d}:i).filter(i=>i.quantity>0));
  async function submit(){ if(!cart.length||sending||!name.trim())return; setSending(true); try{const r=await fetch("/api/menu/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer_name:name.trim(),notes:notes.trim(),items:cart.map(i=>({product_id:i.product.id,quantity:i.quantity,options:{}}))})}); const x=await r.json(); if(!r.ok)throw new Error(x.error||"Unable to place order"); setSuccess(x); setCart([]); setCartOpen(false);}catch(e:any){alert(e.message)}finally{setSending(false)} }
  if(success)return <main className="wm-page"><section className="wm-success"><div className="wm-success-icon"><Check size={42}/></div><p className="wm-eyebrow">WISE MENU</p><h1>Order Sent!</h1><p>Your order <b>{success.order_no}</b> has been sent to the kitchen.</p><div className="wm-success-total">₱{Number(success.total||0).toFixed(2)}</div><button onClick={()=>setSuccess(null)}>Back to Menu</button></section></main>;
  return <main className="wm-page"><header className="wm-header"><div><div className="wm-logo">WISE <span>MENU</span></div><small>Scan. Select. Send your order.</small></div><button className="wm-cart" onClick={()=>setCartOpen(true)}><ShoppingBag size={21}/><span>{count}</span></button></header><div className="wm-search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search menu..."/></div><nav className="wm-cats">{categories.map(c=><button className={category===c?"active":""} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</nav>{loading?<div className="wm-loading">Loading menu…</div>:<section className="wm-grid">{filtered.map(p=><article className="wm-card" key={p.id}><div className="wm-media">{p.video_url?<video src={p.video_url} autoPlay muted loop playsInline preload="metadata"/>:p.image_url?<img src={p.image_url} alt=""/>:<div className="wm-placeholder">WISE</div>}<button className="wm-add" onClick={()=>add(p)}><Plus size={19}/></button></div><div className="wm-card-body"><small>{p.category||"Menu"}</small><h2>{p.name}</h2><p>{p.description||""}</p><strong>₱{Number(p.price).toFixed(2)}</strong></div></article>)}</section>}{!cartOpen&&count>0&&<button className="wm-floating-cart" onClick={()=>setCartOpen(true)}><ShoppingBag size={20}/> View Order <b>₱{total.toFixed(2)}</b></button>}{cartOpen&&<div className="wm-overlay"><aside className="wm-drawer"><header><div><small>WISE MENU</small><h2>Your Order</h2></div><button onClick={()=>setCartOpen(false)}><X/></button></header><div className="wm-cart-list">{cart.map(i=><div className="wm-cart-row" key={i.product.id}><div><b>{i.product.name}</b><small>₱{Number(i.product.price).toFixed(2)} each</small></div><div className="wm-qty"><button onClick={()=>change(i.product.id,-1)}><Minus size={15}/></button><b>{i.quantity}</b><button onClick={()=>change(i.product.id,1)}><Plus size={15}/></button></div></div>)}</div><div className="wm-checkout"><label>Your Name <span>*</span></label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your name" required/><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Special instructions (optional)"/><div className="wm-total"><span>Total</span><b>₱{total.toFixed(2)}</b></div><button disabled={sending||!cart.length||!name.trim()} onClick={submit}>{sending?"Sending…":"Send Order to Kitchen"}</button></div></aside></div>}</main>;
}
